const CHECK_USER_SESSION = 'CHECK_USER_SESSION'
const VERIFY_USER = 'VERIFY_USER'
const LOGOUT_USER = 'LOGOUT_USER'
const SET_TODOS = 'SET_TODOS'
const ADD_TODOS = 'ADD_TODOS'
const CHANGE_TODO = 'CHANGE_TODO'

export { 
  CHECK_USER_SESSION, 
  VERIFY_USER, 
  LOGOUT_USER,
  SET_TODOS,
  ADD_TODOS,
  CHANGE_TODO,
}
