const CHECK_USER_SESSION = 'CHECK_USER_SESSION'
const VERIFY_USER = 'VERIFY_USER'
const LOGOUT_USER = 'LOGOUT_USER'
const SET_TODOS = 'SET_TODOS'
const ADD_TODO = 'ADD_TODO'
const CHANGE_TODO = 'CHANGE_TODO'
const REMOVE_TODO = 'REMOVE_TODO'
const SET_NOTES = 'SET_NOTES'
const ADD_NOTE = 'ADD_NOTE'
const CHANGE_NOTE = 'CHANGE_NOTE'
const REMOVE_NOTE = 'REMOVE_NOTE'

export { 
  CHECK_USER_SESSION, 
  VERIFY_USER, 
  LOGOUT_USER,
  SET_TODOS,
  ADD_TODO,
  CHANGE_TODO,
  REMOVE_TODO,
  SET_NOTES,
  ADD_NOTE,
  CHANGE_NOTE,
  REMOVE_NOTE,
}
